=== anhallbe/programming-web-services/pws-hw1/xml/CompanyInfo.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="company" type="companyType"/>
    <xs:complexType name="companyType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="keywords" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="availablePositions" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="position" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                    <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== anhallbe/programming-web-services/pws-hw1/src/pws/hw1/xml/cauldrons-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<company
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/andreas/Development/programming-web-services/pws-hw1/src/pws/hw1/xml/CompanyInfo.xsd'>
    <name>Cauldrons Inc.</name>
    <description>A couldron manufacturing company based in Diagon Alley.</description>
    <keywords>magic, cauldron, money, manufacturing</keywords>
    <availablePositions>
        <position>
            <title>Cashier</title>
            <description>Looking for an experienced person with interests in sales, money laundering and magic.</description>
        </position>
    </availablePositions>

</company>
