=== anhallbe/programming-web-services/pws-hw1/xml/EmploymentRecord.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="employmentRecord">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="surname" minOccurs="1" maxOccurs="1" type="xs:string"/>
                <xs:element name="lastname" minOccurs="1" maxOccurs="1" type="xs:string"/>
                <xs:element name="employments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="companyName" type="xs:string"/>
                            <xs:element name="start" type="xs:date"/>
                            <xs:element name="end" type="xs:date"/>
                            <xs:element name="monthlySalary" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== anhallbe/programming-web-services/pws-hw1/src/pws/hw1/xml/ronald-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<employmentRecord
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:src/pws/hw1/xml/EmploymentRecord.xsd'>
    <surname>Weasley</surname>
    <lastname>Ronald</lastname>
    <employments>
        <employment>
            <companyName>Cauldrons Inc.</companyName>
            <start>2010-12-13</start>
            <end>2011-12-13</end>
            <monthlySalary>10000</monthlySalary>
        </employment>
        <employment>
            <companyName>Weasley Tricks and Candy Canes</companyName>
            <start>2005-12-13</start>
            <end>2008-12-13</end>
            <monthlySalary>7000</monthlySalary>
        </employment>
        <employment>
            <companyName>Diagon Alley Custodials</companyName>
            <start>2012-12-13</start>
            <end>2014-12-13</end>
            <monthlySalary>12000</monthlySalary>
        </employment>
    </employments>

</employmentRecord>
