=== anhallbe/programming-web-services/pws-hw1/src/pws/hw1/xml/CV.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="cv" type="cvType"/>
    <xs:complexType name="cvType">
        <xs:sequence>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="lastname" type="xs:string"/>
            <xs:element name="birthdate" type="xs:date"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value=".*@{1}[a-z || 0-9]+\.[a-z]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="about" type="xs:string"/>
            <xs:element name="references">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="reference" minOccurs="2" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="refName" type="xs:string" maxOccurs="1"/>
                                    <xs:element name="refAbout" type="xs:string" maxOccurs="1"/>
                                    <xs:element name="refContactInfo" type="xs:string" maxOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== anhallbe/programming-web-services/pws-hw1/src/pws/hw1/xml/ronald-cv.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/andreas/Development/programming-web-services/pws-hw1/src/pws/hw1/xml/CV.xsd'>
    <surname>Ronald</surname>
    <lastname>Weasley</lastname>
    <birthdate>1990-12-13</birthdate>
    <address>Crow's Nest 2</address>
    <city>Muggleton</city>
    <country>UK</country>
    <phone>0101010101</phone>
    <email>ron@weasleys.com</email>
    <about>Just another red-headed wizard.</about>
    <references>
        <reference>
            <refName>George Weasley</refName>
            <refAbout>My brother George</refAbout>
            <refContactInfo>george@weasleys.com</refContactInfo>
        </reference>
        <reference>
            <refName>Fred Weasley</refName>
            <refAbout>My brother Fred</refAbout>
            <refContactInfo>fred@weasleys.com</refContactInfo>
        </reference>
    </references>

</cv>
